# config/settings.yml
defaults: &defaults
app_name: "Sample Rails App"
user_name: "Michael Hartl"
admin_email: "admin@example.com"
items_per_page: 10 
rails_logo_alt: "Rails logo"
rails_logo_width: "200"
base_title: "Ruby on Rails Tutorial Sample App"
rails_tutorial_text: "Ruby on Rails Tutorial"
rails_tutorial_url: "https://www.railstutorial.org/"
michael_hartl_url: "https://www.michaelhartl.com/"
michael_hartl_text: "Michael Hartl"
railstutorial_news_url: "https://news.railstutorial.org/"
rails_official_url: "https://rubyonrails.org/"
rails_help_url: "https://www.railstutorial.org/help"
rails_book_url: "https://www.railstutorial.org/book"
rails_contact_url: "https://www.railstutorial.org/contact"
learn_enough_url: "https://www.learnenough.com/"
rails_screencast_url: "https://screencasts.railstutorial.org/"
base_avatar_url: "https://www.gravatar.com/avatar"
gravatar_base_url: "https://secure.gravatar.com/avatar"
gravatar_email_url: "http://gravatar.com/emails"
genders:
  - male
  - female
  - other
items_per_page: 10

development:
<<: *defaults
debug_mode: true
api_key: "dev_api_key_123" 

test:
<<: *defaults
debug_mode: false
api_key: "test_api_key_abc"

production:
<<: *defaults
debug_mode: false
api_key: <%= ENV.fetch("PRODUCTION_API_KEY") { "default_prod_key" } %> # Lấy từ biến môi trường
items_per_page: 20 
