# config/settings.yml
defaults: &defaults
app_name: "Sample Rails App"
admin_email: "admin@example.com"
items_per_page: 10 

development:
<<: *defaults
debug_mode: true
api_key: "dev_api_key_123" 

test:
<<: *defaults
debug_mode: false
api_key: "test_api_key_abc"

production:
<<: *defaults
debug_mode: false
api_key: <%= ENV.fetch("PRODUCTION_API_KEY") { "default_prod_key" } %> # Lấy từ biến môi trường
items_per_page: 20 
